import { Product } from "./types/Product";

export const sampleProducts: Product[] = [
  {
    name: "Nike Slim shirt",
    slug: "nike-slim-shirt",
    category: "Shirt",
    image: "../images/p1.jpg",
    price: 120,
    countInStock: 10,
    brand: "Nike",
    rating: 4.5,
    numReviews: 10,
    description: "hight quatity shirt",
  },
  {
    name: "Nike Slim shirt",
    slug: "addidaas-slim-shirt",
    category: "Shirt",
    image: "../images/p1.jpg",
    price: 120,
    countInStock: 10,
    brand: "Nike",
    rating: 4.5,
    numReviews: 10,
    description: "hight quatity shirt",
  },
  {
    name: "Nike Slim shirt",
    slug: "nocvert-slim-shirt",
    category: "Shirt",
    image: "../images/p1.jpg",
    price: 120,
    countInStock: 10,
    brand: "Nike",
    rating: 4.5,
    numReviews: 10,
    description: "hight quatity shirt",
  },
  {
    name: "Nike Slim shirt",
    slug: "balenciaga-slim-shirt",
    category: "Shirt",
    image: "../images/p1.jpg",
    price: 120,
    countInStock: 10,
    brand: "Nike",
    rating: 4.5,
    numReviews: 10,
    description: "hight quatity shirt",
  },
];
